services:
    phpbbmodders.annualstars.listener:
        class: phpbbmodders\annualstars\event\listener
        arguments:
            - @template
            - @user
        tags:
            - { name: event.listener }
 